[package]
name = "taxi"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]

[lib]
name = "taxi"

[dependencies]
rand = "*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
rayon = "0.9"
float-cmp = "0.2"

[target.'cfg(not(windows))'.dependencies]
tui = "*"
termion = "*"

[dev-dependencies]
assert_matches = "1.1"
criterion = "0.1.2"

[[bin]]
name = "taxi"
test = false

[[bench]]
name = "training_session"
harness = false