[package]
name = "taxi"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]

[lib]
name = "taxi"

[dependencies]
rand = "*"
tui = "*"
termion = "*"

[dev-dependencies]
assert_matches = "1.1"

[[bin]]
name = "taxi"
test = false