[package]
name = "taxi"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]

[lib]
name = "taxi"

[dependencies]
rand = "*"
tui = "*"
termion = "*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
rayon = "0.8"
float-cmp = "0.2"

[dev-dependencies]
assert_matches = "1.1"

[[bin]]
name = "taxi"
test = false